### ISSUE TITLE
in 1st question  we need to create array and add data in array for that we use append command ... insert commadn is used for creating list

### ISSUE THREAD

**Issue by ombharamadev** [afiyamujar/day_2#1]
![image](https://github.com/afiyamujar/day_2/assets/150242178/6cdbb996-638d-42c1-94d8-5f4d88bea1b3)

in 1st question  we need to create array and add data in array for that we use append command ... insert commadn is used for creating list

**Comment by afiyamujar** [comment]
I have corrected my mistake 
Thank you !

**Comment by ombharamadev** [comment]
no update in code showing
![image](https://github.com/afiyamujar/day_2/assets/150242178/875317bd-1b70-4d31-a1a8-5473c9c7e0fc)

**Comment by ombharamadev** [comment]
ok done good work

**Comment by afiyamujar** [comment]
Thank you sir!
