### ISSUE TITLE
there is error in output of csv file 

### ISSUE THREAD

**Issue by ombharamadev** [afiyamujar/day_2#2]
![image](https://github.com/afiyamujar/day_2/assets/150242178/ad85c128-eca0-4dc7-8a12-a23c4ec86940)

there is some error in output of csv file

**Comment by afiyamujar** [comment]
I have corrected my mistake
Thank you!

**Comment by ombharamadev** [comment]
you need to remove .py in csv file output only use ".csv" file extesnions
![image](https://github.com/afiyamujar/day_2/assets/150242178/27bc0dc2-e3ba-410f-9999-48a19de80b0c)

**Comment by afiyamujar** [comment]
i removed it sir

**Comment by ombharamadev** [comment]
good
